"""Add more user info

Revision ID: f0d6248bd55c
Revises: 79fb60af6941
Create Date: 2023-03-09 10:51:35.829802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0d6248bd55c'
down_revision = '79fb60af6941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('facebook', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('linkedin', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('twitter', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('github', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('youtube', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('instagram', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('snapchat', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tiktok', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('medium', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('medium')
        batch_op.drop_column('tiktok')
        batch_op.drop_column('snapchat')
        batch_op.drop_column('instagram')
        batch_op.drop_column('youtube')
        batch_op.drop_column('github')
        batch_op.drop_column('twitter')
        batch_op.drop_column('linkedin')
        batch_op.drop_column('facebook')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
