"""Initial migrate

Revision ID: e10e82fd67b4
Revises: 
Create Date: 2023-03-05 13:46:56.860144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e10e82fd67b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_profile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_profile',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=25), nullable=False),
    sa.Column('picture_url', sa.VARCHAR(), nullable=False),
    sa.Column('twitter', sa.VARCHAR(), nullable=False),
    sa.Column('github', sa.VARCHAR(), nullable=False),
    sa.Column('linkedin', sa.VARCHAR(), nullable=False),
    sa.Column('user_bio', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
